/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class SurrealdbNodeEngine {
  execute(data: Uint8Array): Promise<Uint8Array>
  static connect(endpoint: string, opts?: ConnectionOptions): Promise<SurrealdbNodeEngine>
  free(): void
}
